/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
