/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import cli.Console;
import commands.CommandFactory;
import commands.CommandInvoker;
import commands.ICommand;
import list.DoublyLinkedList;
import list.Listable;
import list.SinglyLinkedList;

public class Main {

    public static void main(String[] args) {
        Console console = new Console();
        System.out.println("LinkedList test App\n");
        System.out.println("Select list type before starting the main menu:\n");
        System.out.println("1. SinglyLinkedList");
        System.out.println("2. DoublyLinkedList\n");

        boolean done = false;
        while (!done) {
            int option = console.readIntegerFromStdin("Please enter a number for an option: ");
            Listable<ICommand> commands = null;
            String headline = "";
            switch (option) {
                case 1:
                    headline = "You selected SinglyLinkedList:";
                    commands = CommandFactory.createStudentCommendList(console, new SinglyLinkedList<>());
                    break;
                case 2:
                    headline = "You selected DoublyLinkedList:";
                    commands = CommandFactory.createStudentCommendList(console, new DoublyLinkedList<>());
                    break;
            }

            if (commands != null) {
                done = true;
                System.out.println(System.lineSeparator());
                CommandInvoker invoker = new CommandInvoker(commands, console, headline, true);
                invoker.run();
            }
        }
    }

}
